### ISSUE TITLE
Can't access webpage

### ISSUE THREAD

**Issue by gummibjorn** [degiorgioo/iamdada#1]
![image](https://user-images.githubusercontent.com/11292339/32915365-e86c29e6-cb18-11e7-889a-9f1b5a586868.png)

anyone else experiencing similar issues?
pls help

**Comment by degiorgioo** [comment]
hi @gummibjorn , it will be available soon. I have some changes to do, because my first approach didn't fit my requirements now. 

cheers man 
:beers:
